# 服务端口号
server:
  port: 8206

# MyBatisPlus相关配置
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  # MySQL数据源
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.123.132:3306/gmall_product?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
  # redis相关配置
  redis:
    host: 192.168.123.132
    password:
    database: 0
    port: 6379
  # zipkin链路追踪
  zipkin:
    base-url: http://192.168.123.132:9411
  # RabbitMQ
  rabbitmq:
    host: 192.168.6123.132
    port: 5672
    username: guest
    password: guest
